# SciKit Learn Preprocessing Overview

In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[99, 38],
       [63, 25],
       [65, 23],
       [ 6, 32],
       [24, 96],
       [33, 41],
       [ 0, 24],
       [66, 46],
       [19, 10],
       [32, 24]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
scaler_model.fit(data)

C:\Users\hassan\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [7]:
scaler_model.transform(data)

array([[1.        , 0.3255814 ],
       [0.63636364, 0.1744186 ],
       [0.65656566, 0.15116279],
       [0.06060606, 0.25581395],
       [0.24242424, 1.        ],
       [0.33333333, 0.36046512],
       [0.        , 0.1627907 ],
       [0.66666667, 0.41860465],
       [0.19191919, 0.        ],
       [0.32323232, 0.1627907 ]])

In [8]:
# In one step
result = scaler_model.fit_transform(data)

C:\Users\hassan\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [9]:
result

array([[1.        , 0.3255814 ],
       [0.63636364, 0.1744186 ],
       [0.65656566, 0.15116279],
       [0.06060606, 0.25581395],
       [0.24242424, 1.        ],
       [0.33333333, 0.36046512],
       [0.        , 0.1627907 ],
       [0.66666667, 0.41860465],
       [0.19191919, 0.        ],
       [0.32323232, 0.1627907 ]])

In [10]:
import pandas as pd

In [12]:
data = pd.DataFrame(data=np.random.randint(0,101,(50,4)),columns=['f1','f2','f3','label'])

In [13]:
data.head()

f1  f2  f3  label
0   2   1  31     28
1  70  27  92     28
2  60   3  85     51
3  40  59  11     32
4  36  81  28     94

In [14]:
x = data[['f1','f2','f3']] # Alternatively x = data.drop('label',axis=1)
y = data['label']

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=101)

In [17]:
X_train.shape

(35, 3)

In [18]:
X_test.shape

(15, 3)

In [19]:
y_train.shape

(35,)

In [20]:
y_test.shape

(15,)

## Great Job!